# Generated by Django 5.2.4 on 2025-07-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tujenge_app', '0002_user_name_user_phone_number_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='Uknown', max_length=100),
        ),
    ]
